name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up env
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Cache Bun
        uses: actions/cache@v5
        with:
          path: ~/.bun/install/cache
          key: linux-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            linux-bun-${{ hashFiles('**/bun.lock') }}
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build Linux
        run: make linux
        env:
          VERSION: ${{ env.VERSION }}
      - name: Linux Release
        run: make linux-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}
  deploy-aur:
    name: Deploy to AUR
    needs: build-linux
    runs-on: ubuntu-latest
    container:
      # INFO:  Use Arch image to access updpkgsums
      image: archlinux:latest
    steps:
      - name: Install dependencies
        run: pacman -Syu --noconfirm pacman-contrib git openssh
      - uses: actions/checkout@v5
      - name: Update Version and Checksums
        run: |
          VERSION=${{ github.ref_name }}
          VERSION_NO_V=${VERSION#v}
          sed -i "s/pkgver=.*/pkgver=$VERSION_NO_V/" ./scripts/PKGBUILD
          updpkgsums ./scripts/PKGBUILD
      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v5
        with:
          pkgname: mw-timetrack-bin
          pkgbuild: ./scripts/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to v${{ env.CLEAN_VERSION }}"
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up env
        shell: bash
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Cache Bun
        uses: actions/cache@v5
        with:
          path: ~/.bun/install/cache
          key: windows-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            windows-bun-${{ hashFiles('**/bun.lock') }}
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build Windows
        shell: bash
        run: make windows
        env:
          VERSION: ${{ env.VERSION }}
      - name: Windows Release
        shell: bash
        run: make windows-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}
  build-macos:
    name: Build MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up env
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Cache Bun
        uses: actions/cache@v5
        with:
          path: ~/.bun/install/cache
          key: macos-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            macos-bun-${{ hashFiles('**/bun.lock') }}
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build MacOS
        run: make macos
        env:
          VERSION: ${{ env.VERSION }}
      - name: MacOS Release
        run: make macos-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}
